### jupyter notebook magic

In [1]:
! jupyter notebook

In [2]:
%matplotlib inline

### CPU warning

In [3]:
import os
# 1 all(default), 2 warning & error, 3 error
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

### Hello World

In [4]:
import tensorflow as tf

# 建立運算圖
hello = tf.constant('Hello, Tensorflow.')

# 進行運算

# manual close
session = tf.Session()
print(session.run(hello))
session.close()

# auto close
with tf.Session() as session:
    print(session.run(hello))

b'Hello, Tensorflow.'
b'Hello, Tensorflow.'


### add

#### 3 + 7 = 10

In [5]:
import tensorflow as tf

# Reset the Graph
tf.reset_default_graph()

number1a = tf.constant(3, name='number1a')
number1b = tf.constant(7, name='number1b')
result1 = tf.add(number1a, number1b, name='result1')

print('number1a: ', number1a)
print('number1b: ', number1b)
print('result1: ', result1)

with tf.Session() as session:
    # 全域變數初始化(important)
    session.run(tf.global_variables_initializer())
    print('value: ', session.run(result1))

number1a:  Tensor("number1a:0", shape=(), dtype=int32)
number1b:  Tensor("number1b:0", shape=(), dtype=int32)
result1:  Tensor("result1:0", shape=(), dtype=int32)
value:  10


#### 3 += 7

In [6]:
import tensorflow as tf

tf.reset_default_graph()

number2a = tf.Variable(3)
number2b = tf.constant(7)
result2 = tf.add(number2a, number2b)
assign2 = tf.assign(number2a, result2)

with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    print('result2: ', session.run(result2))
    print('number2a: ', session.run(number2a))
    print('assign2: ', session.run(assign2))
    print('number2a: ', session.run(number2a))

result2:  10
number2a:  3
assign2:  10
number2a:  10


#### 0 += 1 (Loop)

In [7]:
import tensorflow as tf

tf.reset_default_graph()

number3a = tf.Variable(0)
number3b = tf.constant(1)
result3 = tf.add(number3a, number3b)
assign3 = tf.assign(number3a, result3)

with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    for i in range(8):
        value = session.run(assign3)
        print('run:', i + 1, 'times: ', value)
    print('Finally, number3a: ', session.run(number3a))

run: 1 times:  1
run: 2 times:  2
run: 3 times:  3
run: 4 times:  4
run: 5 times:  5
run: 6 times:  6
run: 7 times:  7
run: 8 times:  8
Finally, number3a:  8


### about shape

In [8]:
import tensorflow as tf

tf.reset_default_graph()

# () => shape
# number4a = tf.constant(1) # int32
# number4a = tf.constant(1.0) # float32
number4a = tf.constant(1, dtype=tf.float32) # 0-D
print('number4a shape: ', number4a.shape, number4a)
number4b = tf.ones([]) # 0-D ==> 1.0
print('number4b shape: ', number4b.shape, number4b)
number4c = tf.ones([1]) # 1-D ==> [1.0] vector
print('number4c shape: ', number4c.shape, number4c)
number4d = tf.ones([3]) # 1-D ==> [1.0, 1.0, 1.0] vector
print('number4d shape: ', number4d.shape, number4d)
number4e = tf.ones([1, 2]) # 2-D ==> [[1.0, 1.0]]
print('number4e shape: ', number4e.shape, number4e)
number4f = tf.ones([2, 3]) # 2-D ==> [[1.0, 1.0, 1.0], [1.0, 1.0, 1.0]]
print('number4f shape: ', number4f.shape, number4f)
"""
[
    [1.0, 1.0, 1.0],
    [1.0, 1.0, 1.0]
]
"""

# [] => value
with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    print('number4a: ', session.run(number4a))
    print('number4b: ', session.run(number4b))
    print('number4c: ', session.run(number4c))
    print('number4d: ', session.run(number4d))
    print('number4e: ', session.run(number4e))
    print('number4f:\n', session.run(number4f))

number4a shape:  () Tensor("Const:0", shape=(), dtype=float32)
number4b shape:  () Tensor("ones:0", shape=(), dtype=float32)
number4c shape:  (1,) Tensor("ones_1:0", shape=(1,), dtype=float32)
number4d shape:  (3,) Tensor("ones_2:0", shape=(3,), dtype=float32)
number4e shape:  (1, 2) Tensor("ones_3:0", shape=(1, 2), dtype=float32)
number4f shape:  (2, 3) Tensor("ones_4:0", shape=(2, 3), dtype=float32)
number4a:  1.0
number4b:  1.0
number4c:  [1.]
number4d:  [1. 1. 1.]
number4e:  [[1. 1.]]
number4f:
 [[1. 1. 1.]
 [1. 1. 1.]]


### 1-D operations

In [9]:
import tensorflow as tf

tf.reset_default_graph()

number5a = tf.constant([1, 3, 5, 7, 9, 11])
number5b = tf.constant([1, 3, 5, 7, 9, 11])
print('number5a shape: ', number5a.shape) # [6]

# Broadcast(for 0-D & 1-D)
number5c = tf.constant(3) # 0-D [] ==> [3, 3, 3, 3, 3, 3]
number5d = tf.constant([3]) # 1-D [] ==> [3, 3, 3, 3, 3, 3]

# ValueError: Dimensions must be equal, but are 6 and 5 for 'Add_3' (op: 'Add') with input shapes: [6], [5].
result5b = tf.add(number5a, number5b)
result5c = tf.add(number5a, number5c)
result5d = tf.add(number5a, number5d)

result5e = tf.subtract(number5a, number5d)
result5f = tf.multiply(number5a, number5d)
result5g = tf.div(number5a, number5d) # int32
result5h = tf.divide(number5a, number5d) # float32

with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    print('result5b: ', session.run(result5b))
    print('result5c: ', session.run(result5c))
    print('result5d: ', session.run(result5d))
    print('result5e: ', session.run(result5e))
    print('result5f: ', session.run(result5f))
    print('result5g: ', session.run(result5g))
    print('result5h: ', session.run(result5h))

number5a shape:  (6,)
result5b:  [ 2  6 10 14 18 22]
result5c:  [ 4  6  8 10 12 14]
result5d:  [ 4  6  8 10 12 14]
result5e:  [-2  0  2  4  6  8]
result5f:  [ 3  9 15 21 27 33]
result5g:  [0 1 1 2 3 3]
result5h:  [0.33333333 1.         1.66666667 2.33333333 3.         3.66666667]


### Matrix

In [10]:
import tensorflow as tf

tf.reset_default_graph()

matrix6a = tf.constant([[2, 3], [1, 4], [7, 2]])
matrix6b = tf.constant([[1, 4, 7], [3, 6, 9]])

print('matrix6a shape: ', matrix6a.shape) # [3, 2]
print('matrix6b shape: ', matrix6b.shape) # [2, 3]

# shape: [A, B] x [B, C] ==> [A, C], B要相等
result6 = tf.matmul(matrix6a, matrix6b)

with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    print('result6:\n', session.run(result6)) # [3, 3]

matrix6a shape:  (3, 2)
matrix6b shape:  (2, 3)
result6:
 [[11 26 41]
 [13 28 43]
 [13 40 67]]


### Matrix reshape

In [11]:
import tensorflow as tf

tf.reset_default_graph()

matrix7a = tf.constant([1, 3, 7, 4, 9, 13, 17, 23]) #[8]
matrix7b = tf.reshape(matrix7a, [4, 2])
matrix7c = tf.reshape(matrix7a, [2, 4])
matrix7d = tf.reshape(matrix7a, [8, 1])
matrix7e = tf.reshape(matrix7a, [1, 8])
matrix7f = tf.reshape(matrix7c, [-1]) # 一律展開

with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    print('matrix7a: ', session.run(matrix7a))
    print('matrix7b:\n', session.run(matrix7b))
    print('matrix7c:\n', session.run(matrix7c))
    print('matrix7d:\n', session.run(matrix7d))
    print('matrix7e: ', session.run(matrix7e))
    print('matrix7f: ', session.run(matrix7f))

matrix7a:  [ 1  3  7  4  9 13 17 23]
matrix7b:
 [[ 1  3]
 [ 7  4]
 [ 9 13]
 [17 23]]
matrix7c:
 [[ 1  3  7  4]
 [ 9 13 17 23]]
matrix7d:
 [[ 1]
 [ 3]
 [ 7]
 [ 4]
 [ 9]
 [13]
 [17]
 [23]]
matrix7e:  [[ 1  3  7  4  9 13 17 23]]
matrix7f:  [ 1  3  7  4  9 13 17 23]


### Placeholder

In [12]:
import tensorflow as tf

tf.reset_default_graph()

matrix8a = tf.constant([1, 3, 7, 4, 9, 13, 17, 23])
placeholder8b = tf.placeholder(tf.int32, [8])
placeholder8c = tf.placeholder(tf.int32, [8])
placeholder8d = tf.placeholder(tf.int32, [None])

result8a = tf.multiply(matrix8a, placeholder8b)
result8b = tf.multiply(result8a, placeholder8c)
result8c = tf.multiply(result8b, placeholder8d)

with tf.Session() as session:
    session.run(tf.global_variables_initializer())
    value = session.run(result8a, feed_dict = {
        placeholder8b: [2, 4, 7, 1, 9, 11, 13, 15]
    })
    print('result8a: ', value)
    value = session.run(result8b, feed_dict = {
        placeholder8b: [2, 4, 7, 1, 9, 11, 13, 15],
        placeholder8c: [6, 2, 2, 3, 8, 21, 5, 11]
    })
    print('result8b: ', value)
    value = session.run(result8c, feed_dict = {
        placeholder8b: [2, 4, 7, 1, 9, 11, 13, 15],
        placeholder8c: [6, 2, 2, 3, 8, 21, 5, 11],
        placeholder8d: [2]
    })
    print('result8c: ', value)

result8a:  [  2  12  49   4  81 143 221 345]
result8b:  [  12   24   98   12  648 3003 1105 3795]
result8c:  [  24   48  196   24 1296 6006 2210 7590]
